add: start dashboard
fknop/oscareducation pull request #22
Opened 2017-11-01 18:53 UTC by jhennecart

2017-11-01 19:28 UTC, fknop requested changes

2017-11-01 19:28 UTC, fknop commented on templates/forum/dashboard.haml
> +-load lesson_tags
Necessary to load lesson_tags ?

2017-11-01 19:28 UTC, fknop commented on templates/forum/dashboard.haml
> +	            %td {{thread.author}}
I think it should be thread.author.username

2017-11-01 19:28 UTC, fknop commented on templates/forum/dashboard.haml
> +	            %td {{thread.skills}}
It won't work like that as skills is a list, it needs a loop as well

2017-11-01 19:29 UTC, fknop commented
Could you also add a screenshot ?

2017-11-01 21:18 UTC, fknop submitted a review, later dismissed

2017-11-01 21:18 UTC, fknop commented
Good for me.

@mlosicki

2017-11-01 21:42 UTC, fknop commented
Closes #11

2017-11-02 09:34 UTC, mlosicki approved these changes

2017-11-02 10:25 UTC, merged